### ISSUE TITLE
socket.gaierror: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by DrawingProcess** [bjajoh/ntrip_ros_python3#1]
When I was package build and execute ntrip_ros, following error message appears.
: socket.gaierror: [Errno -2] Name or service not known

Maybe I think the problem is socket domain setting or python version.

- python version: 3.8
- ros: noetic
- ubuntu 20.04

Is there anyone who has the following problem?

```bash
$ roslaunch ntrip_ros ntrip_ros.launch
... logging to /home/ubuntu/.ros/log/0ef656bc-173b-11ee-853d-5dd13f6f32b8/roslaunch-ubuntu-96737.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:46117/

SUMMARY
========

CLEAR PARAMETERS
 * /ublox_gps/

PARAMETERS
 * /ntrip_ros/nmea_gga: $GPGGA,093311.145...
 * /ntrip_ros/ntrip_pass: ngii
 * /ntrip_ros/ntrip_server: vrs3.ngii.go.kr:2101
 * /ntrip_ros/ntrip_stream: VRS-RTCM31
 * /ntrip_ros/ntrip_user: tjdwns0714
 * /ntrip_ros/rtcm_topic: /ublox_gps/rtcm
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /ublox_gps/debug: 1
 * /ublox_gps/device: /dev/ttyACM0
 * /ublox_gps/frame_id: gps
 * /ublox_gps/publish/all: False
 * /ublox_gps/publish/nav/all: True
 * /ublox_gps/publish/nav/posecef: True
 * /ublox_gps/publish/nav/posllh: True
 * /ublox_gps/publish/nav/relposned: True
 * /ublox_gps/uart1/baudrate: 460800

NODES
  /
    ntrip_ros (ntrip_ros/ntripclient.py)
    ublox_gps (ublox_gps/ublox_gps)

auto-starting new master
process[master]: started with pid [96757]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 0ef656bc-173b-11ee-853d-5dd13f6f32b8
process[rosout-1]: started with pid [96781]
started core service [/rosout]
process[ublox_gps-2]: started with pid [96789]
process[ntrip_ros-3]: started with pid [96790]
[ INFO] [1688125294.126088756]: U-Blox: Opened serial port /dev/ttyACM0
[DEBUG] [1688125294.131758900]: Configuring UART1 baud rate: 460800, In/Out Protocol: 7 / 1
[DEBUG] [1688125294.135883415]: EXT CORE 1.00 (f10c36), HW VER: 00190000
[DEBUG] [1688125294.136180767]: ROM BASE 0x118B2060
[DEBUG] [1688125294.136354063]: FWVER=HPG 1.13
[DEBUG] [1688125294.136491192]: PROTVER=27.12
[DEBUG] [1688125294.136614711]: MOD=ZED-F9P
[DEBUG] [1688125294.136745081]: GPS;GLO;GAL;BDS
[DEBUG] [1688125294.136869877]: SBAS;QZSS
[ INFO] [1688125294.137180414]: U-Blox Firmware Version: 8
[DEBUG] [1688125294.148962164]: Trying to publish message of type [diagnostic_msgs/DiagnosticArray/60810da900de1dd6ddd437c3503511da] on a publisher with type [diagnostic_msgs/DiagnosticArray/60810da900de1dd6ddd437c3503511da]
[ INFO] [1688125294.149855182]: U-Blox configured successfully.
[DEBUG] [1688125294.150109571]: Subscribing to U-Blox messages
[DEBUG] [1688125294.190286633]: Configuring INF messages
[DEBUG] [1688125295.024010553]: Trying to publish message of type [ublox_msgs/NavPVT/10f57b0db1fa3679c06567492fa4e5f2] on a publisher with type [ublox_msgs/NavPVT/10f57b0db1fa3679c06567492fa4e5f2]
[DEBUG] [1688125295.026398199]: Trying to publish message of type [sensor_msgs/NavSatFix/2d3a8cd499b9b4a0249fb98fd05cfa48] on a publisher with type [sensor_msgs/NavSatFix/2d3a8cd499b9b4a0249fb98fd05cfa48]
[DEBUG] [1688125295.029303419]: Trying to publish message of type [geometry_msgs/TwistWithCovarianceStamped/8927a1a12fb2607ceea095b2dc440a96] on a publisher with type [geometry_msgs/TwistWithCovarianceStamped/8927a1a12fb2607ceea095b2dc440a96]
[DEBUG] [1688125295.032165287]: Trying to publish message of type [ublox_msgs/NavPOSECEF/6f1f4f9473d5586f7fa1427a3c53cee9] on a publisher with type [ublox_msgs/NavPOSECEF/6f1f4f9473d5586f7fa1427a3c53cee9]
[DEBUG] [1688125295.035075915]: Trying to publish message of type [ublox_msgs/NavSAT/e8ea6afd23cb79e7e7385313416d9c15] on a publisher with type [ublox_msgs/NavSAT/e8ea6afd23cb79e7e7385313416d9c15]
[DEBUG] [1688125295.037643228]: Trying to publish message of type [ublox_msgs/NavSTATUS/68047fb8ca04a038a6b031cd1a908762] on a publisher with type [ublox_msgs/NavSTATUS/68047fb8ca04a038a6b031cd1a908762]
[DEBUG] [1688125295.040564596]: Trying to publish message of type [ublox_msgs/NavCLOCK/a9acfdf2e7ac2bf086926ae4e6a182a0] on a publisher with type [ublox_msgs/NavCLOCK/a9acfdf2e7ac2bf086926ae4e6a182a0]
[DEBUG] [1688125295.043019464]: Trying to publish message of type [ublox_msgs/NavRELPOSNED/230f179ad5d03f7dffe9babdd98b23cc] on a publisher with type [ublox_msgs/NavRELPOSNED/230f179ad5d03f7dffe9babdd98b23cc]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/catkin_ws/src/ublox_f9p/ntrip_ros_python3/scripts/ntripclient.py", line 63, in run
    connection.request('GET', '/'+self.ntc.ntrip_stream, self.ntc.nmea_gga, headers)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by DrawingProcess** [comment]
I just fixit. The problem was simply caused by entering the wrong 'ntrip_server' in the launch file.
